-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Gegenereerd op: 30 dec 2025 om 16:00
-- Serverversie: 10.4.32-MariaDB
-- PHP-versie: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `onderwijs_instelling_avg`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `avg_register`
--

CREATE TABLE `avg_register` (
  `id` int(11) NOT NULL,
  `verwerkingsactiviteit` varchar(500) NOT NULL,
  `doel_van_de_verwerking` text NOT NULL,
  `wettelijke_grondslag` varchar(300) NOT NULL,
  `categorieen_persoonsgegevens` text NOT NULL,
  `categorieen_betrokkenen` varchar(300) NOT NULL,
  `categorieen_ontvangers` varchar(300) NOT NULL,
  `bewaartermijnen` varchar(200) NOT NULL,
  `risiconiveau` enum('laag','middel','hoog') NOT NULL,
  `technische_maatregelen` text NOT NULL,
  `organisatorische_maatregelen` text NOT NULL,
  `dpia_vereist` enum('ja','nee') NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Gegevens worden geëxporteerd voor tabel `avg_register`
--

INSERT INTO `avg_register` (`id`, `verwerkingsactiviteit`, `doel_van_de_verwerking`, `wettelijke_grondslag`, `categorieen_persoonsgegevens`, `categorieen_betrokkenen`, `categorieen_ontvangers`, `bewaartermijnen`, `risiconiveau`, `technische_maatregelen`, `organisatorische_maatregelen`, `dpia_vereist`, `created_at`, `updated_at`) VALUES
(1, 'Inschrijving nieuwe leerlingen', 'Registreren van nieuwe leerlingen in het leerlingvolgsysteem en administratie', 'Wettelijke verplichting (Leerplichtwet); Uitvoering overeenkomst', 'Naam, adres, geboortedatum, BSN, nationaliteit, contactgegevens ouders, gezondheidsgegevens (indien relevant), onderwijshistorie', 'Leerlingen, ouders/verzorgers', 'Administratie, mentoren, zorgcoördinator, DUO (BRON)', '5 jaar na uitschrijving of 2 jaar na meerderjarigheid', 'middel', 'Encryptie van gevoelige gegevens, tweefactorauthenticatie voor administratie, logging toegang tot BSN-gegevens', 'Privacyverklaring bij inschrijving, training administratief medewerkers, verwerkersovereenkomsten', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(2, 'Aanmelding via OnderwijsTransparant (OT)', 'Digitale aanmelding en plaatsing leerlingen', 'Wettelijke verplichting; Uitvoering overeenkomst', 'Naam, adres, geboortedatum, BSN, onderwijskundig rapport, advies basisonderwijs', 'Leerlingen, ouders', 'Administratie, OT systeem, basisscholen (doorverwijzing)', '1 jaar na plaatsingbesluit', 'middel', 'Beveiligde API-koppeling, encryptie in transit, toegangscontrole OT-portal', 'OT-protocol, gegevensminimalisatie, ouders informeren over gegevensuitwisseling', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(3, 'Leerlingdossier beheer', 'Bijhouden en beheren van volledige leerlingdossiers', 'Wettelijke verplichting (Wet op het voortgezet onderwijs); Uitvoering overeenkomst', 'Persoonlijke gegevens, onderwijsprestaties, rapporten, testresultaten, gespreksverslagen, zorgdocumentatie, strafregistraties', 'Leerlingen', 'Mentoren, docenten, zorgteam, schoolleiding, inspectie (indien vereist)', '5 jaar na uitschrijving', 'hoog', 'Rolgebaseerd toegangsbeheer, versleutelde opslag, audit logging, automatische backup', 'Functiescheiding, autorisatiebeleid, periodieke dossierreviews, inzagerecht procedures', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(4, 'Cijfers administratie', 'Registreren en beheren van toetsresultaten en rapportcijfers', 'Uitvoering overeenkomst; Wettelijke verplichting', 'Cijfers, toetsresultaten, beoordelingen, voortgangsinformatie', 'Leerlingen', 'Docenten, mentoren, ouders (via ouderportaal), administratie', '2 jaar na diplomering of uitschrijving', 'middel', 'Beveiligd cijfersysteem, encryptie van dataopslag, logging wijzigingen', 'Cijferbeleid, wijzigingsprotocollen, beperkte toegang voor docenten', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(5, 'Afwezigheidsregistratie', 'Registreren en verwerken van ziekteverzuim en afwezigheid', 'Wettelijke verplichting (leerplicht); Vitale belangen', 'Naam, datum, reden afwezigheid, verzuimduur, medische gegevens (bij ziekte)', 'Leerlingen', 'Administratie, mentoren, zorgteam, leerplichtambtenaar', '2 jaar na registratie', 'middel', 'Digitale verzuimregistratie met encryptie, geautomatiseerde meldingen bij zorgwekkend verzuim', 'Verzuimprotocol, privacy bij medische gegevens, meldplicht leerplicht', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(6, 'Zorgdossier en begeleiding', 'Documenteren van zorgbehoeften en begeleidingstrajecten', 'Uitvoering overeenkomst; Toestemming ouders/leerling', 'Zorgbehoefte, testresultaten, handelingsplannen, gespreksverslagen, medische informatie, bijzondere persoonsgegevens', 'Leerlingen met zorgbehoeften', 'Zorgcoördinator, mentoren, docenten, externe zorgverleners, ouders', '5 jaar na uitschrijving', 'hoog', 'Aparte beveiligde omgeving, sterke encryptie, strikt toegangsbeheer, logging alle toegang', 'Zorgprotocol, toestemmingsvereiste voor uitwisseling, functioneel toezichthouder zorg', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(7, 'Passend onderwijs en ontwikkelingsperspectief', 'Opstellen en bijhouden van ontwikkelingsperspectiefplannen', 'Wettelijke verplichting (Passend Onderwijs); Toestemming ouders', 'Leerprestaties, capaciteiten, beperkingen, doelen, bijzondere persoonsgegevens', 'Leerlingen in traject passend onderwijs', 'Zorgteam, docenten, samenwerkingsverband, ouders, eventueel jeugdzorg', '5 jaar na uitschrijving', 'hoog', 'Versleutelde documentopslag, toegang op basis van strikte noodzaak, watermerken op documenten', 'OPP-procedure, oudertoestemming verplicht, periodieke evaluatie, beperkte kring ontvangers', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(8, 'Disciplinaire maatregelen registratie', 'Registreren van ordemaatregelen en disciplinaire acties', 'Gerechtvaardigd belang; Wettelijke verplichting', 'Naam, overtreding, maatregel, datum, gespreksverslagen', 'Leerlingen met disciplinaire maatregelen', 'Schoolleiding, mentoren, zorgteam, ouders', '1 jaar na afronding maatregel', 'middel', 'Beperkte toegang, encryptie, automatische verwijdering na termijn', 'Ordereglement, proportionaliteit, ouders informeren, registratiebeleid', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(9, 'Examenadministratie', 'Registreren en verwerken van examenresultaten en diplomering', 'Wettelijke verplichting (Examens); Uitvoering overeenkomst', 'Naam, examencijfers, examenwerk, diploma gegevens, identificatiegegevens', 'Examendeelnemers', 'Examencommissie, docenten, DUO, administratie', 'Diploma\'s: 30 jaar; Overige examenadministratie: 5 jaar na examen', 'hoog', 'Beveiligde examenomgeving, digitale handtekening diploma\'s, encryptie tijdens uitwisseling', 'Examenreglement, fraude preventie, gescheiden verantwoordelijkheden examencommissie', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(10, 'Ouderportaal toegang', 'Faciliteren van online inzage voor ouders in vorderingen en absentie', 'Toestemming ouders; Uitvoering overeenkomst', 'Naam ouder, e-mail, relatie tot leerling, inloggegevens, gegevens over kind (cijfers, absentie)', 'Ouders/verzorgers, leerlingen', 'Ouders zelf, administratie (beheer)', 'Tot intrekking toegang of einde leerlingrelatie', 'middel', 'Tweefactorauthenticatie, beveiligde inlog, encryptie van communicatie, sessiebeheer', 'Toegangsprotocol ouders, privacyverklaring portaal, beveiligingsinstructies ouders', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(11, 'Magister/Elo gebruik', 'Gebruik van leerlingvolgsysteem en elektronische leeromgeving', 'Uitvoering overeenkomst; Wettelijke verplichting', 'Leerlinggegevens, gebruikersactiviteiten, inleveropdrachten, communicatie, cijfers', 'Leerlingen, docenten', 'Docenten, leerlingen onderling, ouders (beperkt), systeembeheer', 'Actieve periode + 1 jaar', 'middel', 'Encryptie dataopslag, toegangscontrole, logging gebruikersactiviteiten, automatische backup', 'Acceptable use policy, privacy training gebruikers, meldpunt misbruik', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(12, 'Leerlingenvervoer', 'Organiseren en registreren van aangepast leerlingenvervoer', 'Wettelijke verplichting (gemeente); Vitale belangen', 'Naam, adres, beperkingen, medische informatie, vervoersschema, contactgegevens ouders', 'Leerlingen met recht op leerlingenvervoer', 'Gemeente, vervoersbedrijf, schooladministratie, ouders', '1 jaar na beëindiging vervoer', 'hoog', 'Versleutelde gegevensuitwisseling, beperkte gegevens voor vervoerder, apart systeem voor medische info', 'Samenwerkingsovereenkomst gemeente, minimale gegevensuitwisseling, toestemming ouders vereist', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(13, 'Schoolfotografie', 'Maken en verspreiden van schoolfoto\'s', 'Toestemming ouders/leerling; Gerechtvaardigd belang', 'Gezichtsafbeeldingen, naam, klas, schooljaar', 'Leerlingen, personeel', 'Fotograaf, ouders, schoolarchief', 'Tot intrekking toestemming of 10 jaar voor archief', 'middel', 'Watermerken op digitale foto\'s, beveiligde opslag, beperkte toegang tot originelen', 'Toestemmingsformulier foto\'s, opt-out mogelijkheid, gebruik beperkingen communiceren', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(14, 'Schoolkamp en excursies', 'Organiseren en begeleiden van meerdaagse schoolactiviteiten', 'Uitvoering overeenkomst; Vitale belangen', 'Naam, medische informatie (allergieën, medicatie), noodcontacten, verzekeringsgegevens, toestemming formulieren', 'Deelnemende leerlingen', 'Begeleiders, accommodatie, vervoerder, ouders', '6 maanden na activiteit', 'hoog', 'Versleutelde lijsten, fysieke kopieën beveiligd, beperkte toegang tot medische info', 'Veiligheidsprotocol, medische gegevens alleen voor begeleiders, vernietiging na activiteit', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(15, 'Stagebegeleiding en BPV', 'Begeleiden en beoordelen van leerlingen tijdens stage', 'Uitvoering overeenkomst; Wettelijke verplichting (onderwijsprogramma)', 'Naam, contactgegevens, stagebedrijf, beoordelingen, aanwezigheid, leerdoelen', 'Stageleerlingen', 'Stagebegeleiders school, stagebedrijf, examencommissie', '2 jaar na afronding stage', 'middel', 'Beveiligde stageportaal, encryptie beoordelingen, logging uitwisseling bedrijven', 'Stageovereenkomst met privacy clausules, beperkte gegevens naar bedrijf, toestemming leerling', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(16, 'Leerlingondersteuning en mentoraat', 'Begeleiding door mentor en ondersteuningsgesprekken', 'Uitvoering overeenkomst; Gerechtvaardigd belang', 'Gespreksverslagen, begeleidingsplannen, persoonlijke notities mentor, voortgangsgesprekken', 'Leerlingen', 'Mentoren, zorgteam, ouders (beperkt)', '2 jaar na einde mentorrelatie', 'middel', 'Versleutelde notitiesysteem, toegangsbeperking per mentor, automatische archivering', 'Mentorprotocol, privacy training mentoren, gedeelde notities alleen indien nodig', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(17, 'Ouderavonden en rapportbesprekingen', 'Organiseren en uitvoeren van contactmomenten met ouders', 'Uitvoering overeenkomst; Gerechtvaardigd belang', 'Afspraken, gespreksverslagen, aandachtspunten, contactgegevens ouders', 'Leerlingen, ouders', 'Docenten, mentoren, ouders', '1 jaar na gesprek', 'laag', 'Digitale agenda met encryptie, beveiligde opslag gespreksverslagen', 'Protocol oudergesprekken, privacy bij gevoelige onderwerpen, notuleren naar behoefte', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(18, 'Studie- en beroepskeuzebegeleiding', 'Begeleiding bij profiel- en studiekeuze', 'Uitvoering overeenkomst; Gerechtvaardigd belang', 'Interesses, capaciteiten, testresultaten, gespreksverslagen, keuzeformulieren', 'Leerlingen', 'Decanen, mentoren, ouders', '2 jaar na uitstroom', 'middel', 'Beveiligde testomgeving, encryptie testresultaten, toegangsbeperking decanen', 'Decanaat protocol, toestemming voor tests, ouders betrekken conform leeftijd', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(19, 'Verwijzing naar externe zorg', 'Doorverwijzing naar jeugdzorg, psychologen of andere hulpverlening', 'Toestemming ouders/leerling; Vitale belangen', 'Naam, reden verwijzing, zorgbehoefte, contactgegevens, bijzondere persoonsgegevens', 'Leerlingen met zorgbehoeften', 'Jeugdzorg, GGZ, schoolmaatschappelijk werk, ouders', '5 jaar na afronding traject', 'hoog', 'Versleutelde uitwisseling, watermerken verwijzingsdocumenten, logging alle uitgaande documenten', 'Verwijsprotocol, expliciete toestemming vereist, DPO-toetsing bij complexe casussen', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(20, 'Gedragsregistratie en incidenten', 'Registreren van gedragsincidenten en veiligheidsmeldingen', 'Wettelijke verplichting (veiligheid); Gerechtvaardigd belang', 'Naam, incidentbeschrijving, betrokkenen, genomen maatregelen, follow-up acties', 'Betrokken leerlingen en personeel', 'Schoolleiding, zorgteam, eventueel politie, ouders', '2 jaar na afhandeling incident', 'hoog', 'Beveiligd incidentsysteem, logging alle toegang, encryptie gevoelige beschrijvingen', 'Veiligheidsprotocol, meldplicht ernstige incidenten, privacy bij registratie, proportionaliteit', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(21, 'Leerlingmediatie en pestprotocol', 'Registreren en opvolgen van pestincidenten en mediation', 'Wettelijke verplichting (veiligheidsbeleid); Vitale belangen', 'Naam betrokkenen, incidentbeschrijving, gespreksverslagen, afspraken, monitoring', 'Leerlingen betrokken bij pesten of conflict', 'Anti-pestcoördinator, mentoren, zorgteam, ouders betrokkenen', '2 jaar na afronding traject', 'hoog', 'Versleutelde dossieropbouw, strikte toegangscontrole, apart archief voor pestdossiers', 'Pestprotocol, privacy bij gevoelige meldingen, beide partijen horen, zorgvuldige registratie', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(22, 'Medicijnverstrekking en medisch handelen', 'Verstrekken van medicijnen en uitvoeren medische handelingen', 'Vitale belangen; Toestemming ouders', 'Naam, medicatie, dosering, tijdstippen, medische instructies, gezondheidsgegevens', 'Leerlingen met medische behoeften', 'Zorgcoördinator, conciërge, docenten (indien nodig), ouders', 'Duur medicatieverstrekking + 1 jaar', 'hoog', 'Beveiligde medicijnkast, versleutelde digitale registratie, beperkte toegang tot medische info', 'Medicijnprotocol, training personeel, oudertoestemming verplicht, beperkte kring op de hoogte', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(23, 'GGD vaccinaties op school', 'Faciliteren van RVP-vaccinaties door GGD op school', 'Wettelijke verplichting (volksgezondheid); Vitale belingen', 'Naam, geboortedatum, vaccinatiehistorie, toestemming ouders, vaccinatiedatum', 'Leerlingen voor vaccinatie', 'GGD, schooladministratie (beperkt), ouders', '15 jaar na vaccinatie (GGD), school: 1 jaar na activiteit', 'hoog', 'Gegevensuitwisseling via beveiligde portal, minimale gegevens voor school, encryptie', 'Samenwerkingsovereenkomst GGD, ouders informeren over gegevensuitwisseling, minimale rol school', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(24, 'Schoolarts en jeugdgezondheidszorg', 'Faciliteren bezoek schoolarts en JGZ', 'Wettelijke verplichting; Vitale belangen', 'Naam, geboortedatum, gezondheidsgegevens, gespreksverslagen, adviezen', 'Leerlingen bezoekend schoolarts', 'Schoolarts/JGZ, zorgcoördinator (beperkt), ouders', 'JGZ: tot 23e jaar; School: 1 jaar na advies', 'hoog', 'Geen volledige dossiers op school, alleen noodzakelijke informatie versleuteld opgeslagen', 'Duidelijke scheiding school en JGZ, minimale gegevens op school, toestemming voor uitwisseling', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(25, 'Leerlingreisjes en buitenschoolse activiteiten', 'Organiseren dagtrips en educatieve uitjes', 'Uitvoering overeenkomst; Gerechtvaardigd belang', 'Naam, noodcontacten, medische bijzonderheden, toestemmingsformulieren', 'Deelnemende leerlingen', 'Begeleiders, vervoerder, locaties, ouders', '6 maanden na activiteit', 'middel', 'Versleutelde deelnemerslijsten, beperkte medische info op papier, digitale vernietiging na trip', 'Activiteitenprotocol, minimale gegevens meenemen, ouders informeren over gegevensverwerking', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(26, 'Gebruik beeldmateriaal in lessen', 'Maken en gebruiken foto\'s/video\'s voor educatieve doeleinden', 'Toestemming ouders/leerling; Gerechtvaardigd belang', 'Gezichtsafbeeldingen, werkstukken met persoonsgegevens, presentatie-opnames', 'Leerlingen, personeel', 'Docenten, medeleerlingen (klas), ouders (indien gedeeld)', 'Duur onderwijsprogramma of tot intrekking toestemming', 'middel', 'Beperkte opslag, watermerken, toegangsbeperking tot opnames, encryptie', 'Protocol educatief gebruik beeldmateriaal, toestemming per project, leerlingen kunnen alternatief vragen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(27, 'Werving en aanmelding nieuwe leerlingen', 'Recruitment en voorlichting aan potentiële leerlingen', 'Toestemming; Gerechtvaardigd belang', 'Naam, contactgegevens, school van herkomst, interesses, voorlichtingsbezoek registratie', 'Potentiële leerlingen, ouders', 'Wervingsteam, administratie, mentoren toekomstige brugklas', '1 jaar na voorlichting of tot intrekking interesse', 'laag', 'CRM systeem met encryptie, automatische verwijdering na termijn, toegangsbeperking', 'Privacyverklaring bij aanmelding voorlichting, duidelijke communicatie over gegevensgebruik', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(28, 'Open dagen en meeloopdagen', 'Organiseren van open dagen voor potentiële leerlingen', 'Toestemming; Gerechtvaardigd belang', 'Naam, contactgegevens, school van herkomst, voorkeuren, feedback formulieren', 'Bezoekers open dag', 'Wervingsteam, organisatiecomité, gastheer/vrouwen', '1 jaar na evenement', 'laag', 'Digitale inschrijving met encryptie, beperkte gegevensverzameling, automatische cleanup', 'Optionele registratie, duidelijke privacy informatie bij inschrijving', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(29, 'Ouderbijdrage en vrijwillige ouderbijdrage', 'Innen en administreren van ouderbijdragen', 'Toestemming ouders; Uitvoering overeenkomst', 'Naam ouders, betalingsgegevens, bijdragebedrag, betalingshistorie, incassodocumenten', 'Ouders van leerlingen', 'Administratie, penningmeester, eventueel incassobureau, ouders zelf', '7 jaar na laatste betaling (fiscaal)', 'middel', 'Gescheiden financiële administratie, encryptie betaalgegevens, beveiligde betalingslinks', 'Privacybeleid ouderbijdrage, duidelijke communicatie over verwerking, minimale gegevensopslag', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(30, 'Schoolkosten en materialen', 'Verstrekken en factureren van leermiddelen en materialen', 'Uitvoering overeenkomst; Wettelijke verplichting', 'Naam leerling, geleende materialen, facturatie, betalingsgegevens', 'Leerlingen, ouders', 'Administratie, docenten (uitgifte), ouders', '2 jaar na terugname materiaal of betaling', 'laag', 'Materiaalbeheersysteem met beperkte persoonsgegevens, encryptie financiële gegevens', 'Materiaalprotocol, beperkte koppeling leerling-gegevens en materialen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(31, 'Leerlingverzekeringen', 'Administreren en claimen van schoolongevallenverzekering', 'Toestemming ouders; Wettelijke verplichting', 'Naam, geboortedatum, ongevalsbeschrijving, medische gegevens, schadeclaim', 'Leerlingen met ongeval op school', 'Verzekeringsmaatschappij, schooladministratie, ouders', '7 jaar na afhandeling claim', 'hoog', 'Versleutelde claimformulieren, beveiligde uitwisseling verzekeraar, beperkte toegang tot medische info', 'Verzekeringsprotocol, oudertoestemming voor claim, minimale gegevens naar school', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(32, 'Personeelsadministratie', 'Beheer personeelsgegevens, salaris, aanstellingen', 'Wettelijke verplichting; Uitvoering arbeidsovereenkomst', 'Naam, adres, BSN, salarisgegevens, beoordelingen, ziekteverzuim, diplomas, VOG', 'Personeelsleden', 'HR, salarisadministratie, schoolleiding, belastingdienst, pensioenfonds', 'Loongegevens: 7 jaar; Persoonsdossier: 2 jaar na ontslag', 'hoog', 'HR-systeem met strikt toegangsbeheer, encryptie salarisgegevens, logging toegang BSN', 'HR-protocol, privacy personeelsgegevens, beperkte toegang leidinggevenden, DPO-toezicht', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(33, 'Sollicitatieprocedures', 'Werven en selecteren van nieuw personeel', 'Toestemming sollicitant; Uitvoering sollicitatieprocedure', 'CV, motivatiebrief, referenties, gespreksverslagen, beoordelingen, identiteitsbewijs', 'Sollicitanten', 'Selectiecommissie, HR, schoolleiding, referenten', '4 weken na afwijzing, 1 jaar na aanstelling bij succes', 'middel', 'Beveiligde sollicitatiesite, encryptie uploads, automatische verwijdering na termijn', 'Sollicitatieprotocol, privacyverklaring sollicitanten, verwijdering ongewenste documenten', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(34, 'Functionerings- en beoordelingsgesprekken', 'Voeren en documenteren van functioneringsgesprekken', 'Uitvoering arbeidsovereenkomst; Wettelijke verplichting', 'Gespreksverslagen, beoordelingsformulieren, ontwikkelplannen, afspraken', 'Personeelsleden', 'Leidinggevende, HR, personeelslid zelf', '2 jaar na gesprek', 'middel', 'Beveiligde HR-module, versleutelde opslag, toegangsbeperking tot eigen dossier', 'Functioneringsprotocol, inzagerecht medewerker, privacy bij gevoelige onderwerpen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(35, 'Ziekteverzuim personeel', 'Registreren en begeleiden bij ziekteverzuim', 'Wettelijke verplichting (Arbowet); Vitale belangen', 'Naam, ziekteperiode, aard ziekte, contact met bedrijfsarts, reintegratieplan', 'Zieke personeelsleden', 'HR, leidinggevende, bedrijfsarts, Arbo-dienst', '2 jaar na einde verzuim (kort), 10 jaar (lang verzuim)', 'hoog', 'Apart verzuimsysteem, strikte toegangscontrole, encryptie medische informatie', 'Verzuimprotocol, privacy medische gegevens, beperkte toegang, functionaris gegevensbescherming betrokken', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(36, 'VOG aanvraag personeel', 'Aanvragen Verklaring Omtrent Gedrag voor onderwijspersoneel', 'Wettelijke verplichting (Wet BIO)', 'Naam, adres, geboortedatum, BSN, VOG-nummer, functie', 'Personeelsleden in onderwijsfunctie', 'Justis, HR, schoolleiding', 'Duur dienstverband + 1 jaar', 'hoog', 'Fysiek afgesloten archief digitale kopieën, encryptie digitale versies, logging toegang', 'VOG-protocol, strikte noodzaak voor opslag, beperkte kring op de hoogte', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(37, 'Professionalisering en cursussen', 'Registreren en faciliteren van scholing personeel', 'Uitvoering arbeidsovereenkomst; Gerechtvaardigd belang', 'Naam, gevolgde cursussen, certificaten, kosten, evaluaties', 'Personeelsleden', 'HR, leidinggevende, cursusaanbieder, administratie', '5 jaar na voltooiing cursus', 'laag', 'HR-systeem module, encryptie certificaten, beperkte toegang', 'Scholingsbeleid, inzage eigen dossier, beperkte gegevensuitwisseling aanbieder', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(38, 'Interne communicatie en e-mail', 'Dagelijkse communicatie tussen personeelsleden', 'Uitvoering arbeidsovereenkomst; Gerechtvaardigd belang', 'E-mailadressen, communicatie-inhoud, bijlagen, gespreksgeschiedenis', 'Personeelsleden', 'Collega\'s, schoolleiding, systeembeheer (technisch)', '2 jaar na verzending (tenzij archivering vereist)', 'laag', 'E-mail encryptie voor gevoelige informatie, logging beperkt, automatische archivering', 'Communicatieprotocol, privacy awareness, beperkt gebruik voor persoonlijke doeleinden', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(39, 'Roostering en lesuitval', 'Maken en beheren van lesroosters en vervangingen', 'Uitvoering arbeidsovereenkomst; Wettelijke verplichting', 'Naam personeel, beschikbaarheid, lesuren, vakken, vervangingsinformatie', 'Personeelsleden, leerlingen', 'Roostermaker, schoolleiding, docenten, leerlingen (publiek rooster)', '1 jaar na roosterperiode', 'laag', 'Roostersoftware met toegangsbeheer, anonieme weergave waar mogelijk, encryptie gevoelige planning', 'Roosterprotocol, privacy bij persoonlijke omstandigheden, beperkte publieke informatie', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(40, 'ICT gebruikersaccounts', 'Beheren van inlogaccounts voor systemen', 'Uitvoering overeenkomst; Gerechtvaardigd belang (beveiliging)', 'Gebruikersnaam, wachtwoord hash, login historie, IP-adressen, toegangsrechten', 'Personeel, leerlingen (ouderejaars)', 'ICT-beheer, systeembeheerders', '6 maanden na verwijdering account', 'middel', 'Sterke wachtwoord policy, tweefactorauthenticatie voor admin, logging alle loginpogingen', 'Acceptable use policy, regelmatige wachtwoord wijziging, training veilig gebruik', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(41, 'Bring Your Own Device (BYOD)', 'Gebruik privé-apparaten voor werkdoeleinden', 'Toestemming personeel; Gerechtvaardigd belang', 'Device informatie, gebruikspatroon, bedrijfsdata op privé-apparaat, locatie (indien toegang)', 'Personeel met BYOD', 'ICT-beheer, leidinggevende (beperkt)', 'Zolang device in gebruik voor school', 'middel', 'Mobile Device Management, encryptie schooldata, scheiding werk-privé, remote wipe mogelijkheid', 'BYOD-beleid, toestemmingsformulier, duidelijke rechten en plichten, security training', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(42, 'Schoolnetwerk monitoring', 'Monitoren van netwerkgebruik en beveiliging', 'Gerechtvaardigd belang (beveiliging); Wettelijke verplichting', 'IP-adressen, bezochte websites, dataverkeer, gebruikstijden, security incidents', 'Alle netwerkgebruikers', 'ICT-beheer, schoolleiding (bij incidenten)', '3 maanden voor regulier verkeer, 1 jaar voor security incidents', 'middel', 'Anonieme aggregatie waar mogelijk, logging beperkt tot security doeleinden, encryptie logbestanden', 'Monitoring beleid, duidelijke communicatie naar gebruikers, proportionaliteit, geen inhoudelijke monitoring', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(43, 'Back-up en recovery', 'Bescherming tegen dataverlies door back-ups', 'Gerechtvaardigd belang (continuïteit); Wettelijke verplichting', 'Alle persoonsgegevens in primaire systemen', 'Alle betrokkenen', 'ICT-beheer, noodteam bij recovery', 'Volgens back-up schema (dagelijks 30 dagen, maandelijks 1 jaar)', 'hoog', 'Versleutelde back-ups, offsite opslag, toegangscontrole back-ups, regelmatige recovery tests', 'Back-up protocol, recovery plan, minimale retentie, veilige vernietiging oude back-ups', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(44, 'Beveiligingscamera\'s schoolterrein', 'Preventie vandalisme en veiligheid personeel/leerlingen', 'Gerechtvaardigd belang (veiligheid); Wettelijke verplichting', 'Beeldmateriaal, tijdstippen, locaties, eventuele incidenten', 'Alle personen op schoolterrein', 'Beveiliging, schoolleiding, politie bij incidenten', 'Maximaal 4 weken, tenzij incident (max 1 jaar)', 'hoog', 'Beveiligde opslag camera\'s, automatische overschrijving, toegangslogging, watermerken op export', 'Camera protocol, duidelijke aanduiding cameratoezicht, beperkte kring met toegang, periodieke evaluatie', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(45, 'Bezoekersregistratie', 'Registreren van externe bezoekers', 'Wettelijke verplichting (veiligheid); Gerechtvaardigd belang', 'Naam, organisatie, bezoektijd, contactpersoon, identiteitsbewijs (bij toegang gevoelige ruimtes)', 'Externe bezoekers', 'Receptie, beveiliging, gastheer/vrouw', '3 maanden na bezoek', 'middel', 'Digitale bezoekersregistratie met encryptie, automatische verwijdering na termijn', 'Bezoekersprotocol, minimale gegevensverzameling, duidelijk communiceren privacybeleid', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(46, 'Gebruik sociale media door school', 'Communicatie via sociale kanalen', 'Gerechtvaardigd belang; Toestemming voor beeldmateriaal', 'Berichten, reacties, beeldmateriaal (met toestemming), profielinteracties', 'Volgers, leerlingen in beeldmateriaal, reagerende personen', 'Social media manager, communicatieteam, volgers', 'Platform afhankelijk, schoolmaximaal 2 jaar actief beheer', 'middel', 'Toegangsbeperking accounts, monitoring tools, watermerken op eigen beeldmateriaal', 'Social media beleid, toestemmingsprocedure beeldmateriaal, reactieprotocol, privacy awareness', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(47, 'Nieuwsbrief en mailinglijsten', 'Versturen informatie aan ouders en belangstellenden', 'Toestemming; Gerechtvaardigd belang', 'Naam, e-mailadres, relatie tot school, interesseprofiel, openingsstatistieken', 'Ouders, alumni, belangstellenden', 'Communicatieteam, externe mailingdienst (met verwerkersovereenkomst)', 'Tot intrekking toestemming', 'laag', 'Double opt-in systeem, encryptie mailinglijsten, unsubscribe functionaliteit, logging toestemmingen', 'Nieuwsbrief protocol, privacyverklaring bij aanmelding, periodieke toestemming check', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(48, 'Website analytics', 'Analyseren websitebezoek voor verbetering website', 'Toestemming; Gerechtvaardigd belang', 'IP-adres, bezochte pagina\'s, verblijfsduur, device informatie, cookie-ID', 'Websitebezoekers', 'Webmaster, communicatieteam, analytics provider', 'Google Analytics: 26 maanden; Serverlogs: 3 maanden', 'laag', 'IP-anonymisering, cookie-toestemmingssysteem, beperkte data-retentie, opt-out mogelijkheid', 'Cookiebeleid, privacyverklaring website, minimale tracking, regelmatige privacy review', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(49, 'Contactformulieren website', 'Verwerken van vragen en aanmeldingen via website', 'Toestemming; Uitvoering gevraagde dienst', 'Naam, e-mail, telefoon, vraag/inhoud, eventuele bijlagen', 'Websitebezoekers gebruikend contactformulier', 'Relevante afdeling (administratie, werving, etc.), webmaster', '1 jaar na afhandeling', 'laag', 'SSL-encryptie, beveiligde formulierverwerking, automatische verwijdering oude berichten', 'Privacyverklaring bij formulier, duidelijke doel communiceren, beperkte doorgifte', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(50, 'Onderwijsonderzoek en wetenschap', 'Deelnemen aan onderwijsonderzoek en wetenschappelijke studies', 'Toestemming ouders/leerling; Gerechtvaardigd belang (wetenschap)', 'Onderzoeksdata, eventueel persoonsgegevens (afhankelijk studie), toestemmingsformulieren', 'Deelnemende leerlingen, ouders', 'Onderzoekers, school (geanonimiseerde resultaten), wetenschappelijke instelling', 'Volgens onderzoeksprotocol (geanonimiseerd: lang, persoonsgegevens: beperkt)', 'middel', 'Pseudonimisering data, aparte onderzoeksdatabase, encryptie onderzoeksdata, toegangsbeperking onderzoekers', 'Onderzoeksprotocol, informed consent, ethische toetsing, publicatie alleen geaggregeerde data', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(51, 'Benchmarking met andere scholen', 'Vergelijken prestaties en processen met peers', 'Gerechtvaardigd belang; Toestemming (indien persoonsgegevens)', 'Geanonimiseerde prestatie-indicatoren, procesdata, geen individuele leerlinggegevens', 'N.v.t. (geaggregeerd/geanonimiseerd)', 'Benchmark organisatie, schoolleiding, bestuur', '3 jaar na benchmarking ronde', 'laag', 'Anonimisering voor uitwisseling, aggregatie tools, geen koppeling mogelijk naar individuen', 'Benchmark protocol, privacy by design, transparantie naar ouders over deelname', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(52, 'Kwaliteitsonderzoek en tevredenheidsmeting', 'Met tevredenheid leerlingen, ouders en personeel', 'Gerechtvaardigd belang; Toestemming voor deelname', 'Beoordelingen, feedback, suggesties, demografische achtergrond (optioneel)', 'Deelnemende leerlingen, ouders, personeel', 'Kwaliteitsmedewerker, schoolleiding, bestuur (geaggregeerd)', '2 jaar na onderzoek', 'middel', 'Anonieme enquêtes mogelijk, encryptie responsdata, apart systeem voor onderzoeken', 'Onderzoekprotocol, vrijwillige deelname, duidelijke privacy informatie, optionele demografische vragen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(53, 'Klachtenregistratie en afhandeling', 'Behandelen van klachten over schoolfunctioneren', 'Wettelijke verplichting (klachtenregeling); Gerechtvaardigd belang', 'Naam klager, klachtbeschrijving, correspondentie, onderzoek, uitkomst', 'Klagers (leerlingen, ouders, personeel)', 'Klachtencommissie, schoolleiding, bestuur, eventueel inspectie', '2 jaar na afhandeling', 'middel', 'Beveiligd klachtensysteem, encryptie gevoelige klachten, logging toegang', 'Klachtenreglement, privacy bij klachten, onafhankelijke commissie, beperkte toegang tot dossiers', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(54, 'Inzageverzoeken AVG', 'Voldoen aan informatieplicht betrokkenen', 'Wettelijke verplichting (AVG)', 'Verzoek, identiteitsbewijs, uitgeleverde informatie, correspondentie', 'Personen met inzagerecht (leerlingen, ouders, personeel)', 'Functionaris gegevensbescherming, betreffende afdelingen, verzoeker', '3 jaar na afhandeling', 'hoog', 'Audit trail verzoeken, beveiligde verzending informatie, logging verzoeken', 'Inzageprotocol, DPO procedure, termijnbewaking (1 maand), identiteitsverificatie', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(55, 'Verwijderingsverzoeken en recht op vergetelheid', 'Uitvoeren van verwijderingsverzoeken', 'Wettelijke verplichting (AVG)', 'Verzoek, identiteitscontrole, verwijderingslog, uitzonderingen check', 'Verzoekers (leerlingen, ouders, personeel)', 'Functionaris gegevensbescherming, systeembeheerders, betreffende afdelingen', '5 jaar na verwijdering (log van verwijdering)', 'hoog', 'Definitieve verwijdering tools, logging verwijderingsacties, backup management', 'Verwijderingsprotocol, check uitzonderingen (wettelijke bewaarplicht), DPO leiding', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(56, 'Datalekregistratie en melding', 'Registreren en melden van datalekken', 'Wettelijke verplichting (AVG)', 'Incidentbeschrijving, betrokken personen, genomen maatregelen, melding aan autoriteit', 'Getroffen personen bij datalek', 'Functionaris gegevensbescherming, bestuur, Autoriteit Persoonsgegevens (indien meldplicht)', '3 jaar na afhandeling', 'hoog', 'Incident registratiesysteem, encryptie gevoelige incidentgegevens, logging alle acties', 'Datalek protocol, meldplicht procedure, communicatieplan naar betrokkenen, periodieke review', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(57, 'RI&E en Arboregistraties', 'Voldoen aan Arbo-verplichtingen', 'Wettelijke verplichting (Arbowet)', 'Risicoanalyses, ongevallenregistratie, preventiemaatregelen, medewerker consultatie', 'Personeel, leerlingen (indien relevant)', 'Preventiemedewerker, bedrijfsarts, OR, inspectie', 'Laatste versie + 5 jaar', 'middel', 'Versleutelde RI&E documenten, toegangsbeheer, logging wijzigingen', 'RI&E protocol, periodieke evaluatie, medewerker betrokkenheid, privacy bij gezondheidsgegevens', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(58, 'BHV organisatie en training', 'Organiseren bedrijfshulpverlening en training', 'Wettelijke verplichting (Arbowet)', 'Naam BHV\'ers, training historie, inzet bij incidenten, certificaten', 'BHV-personeel', 'BHV-coördinator, schoolleiding, opleider, Arbo-dienst', '5 jaar na einde BHV-lidmaatschap', 'laag', 'BHV administratie systeem, encryptie certificaten, beperkte toegang', 'BHV-protocol, periodieke training, privacy bij inzet registratie', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(59, 'Gebruik surveillancesoftware bij examens', 'Preventie fraude tijdens digitale examens', 'Wettelijke verplichting (examenintegriteit); Gerechtvaardigd belang', 'Beeld en geluid opname, schermopname, toetsaanslagen logging, identiteitsverificatie', 'Examendeelnemers', 'Examencommissie, docenten, systeembeheer (technisch)', '6 maanden na examen, tenzij fraude vermoeden (max 2 jaar)', 'hoog', 'Encryptie van opnames, watermerken, strikte toegangscontrole, automatische verwijdering', 'Examen surveillance protocol, duidelijke informatie aan leerlingen, proportionaliteit, beperkte toegang opnames', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(60, 'Leerlingpanel en leerlingenraad', 'Betrekken leerlingen bij schoolbeleid', 'Toestemming; Gerechtvaardigd belang', 'Naam, klas, functie in raad, contactgegevens, vergaderstukken', 'Leden leerlingenraad', 'Leerlingenraad begeleider, schoolleiding, medeleerlingen', '1 jaar na einde lidmaatschap', 'laag', 'Beperkte gegevensverzameling, versleutelde opslag contactgegevens, aparte communicatiekanalen', 'Leerlingenraad protocol, vrijwillige deelname, privacy bij vergaderstukken', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(61, 'Ouderparticipatie en MR', 'Betrekken ouders bij school via MR en commissies', 'Wettelijke verplichting (WMS); Toestemming', 'Naam, contactgegevens, functie in MR/commissie, vergaderstukken, stemgedrag (MR)', 'Ouders in MR of commissies', 'MR-leden, schoolleiding, bestuur, andere ouders (verslagen)', 'Duur lidmaatschap + 1 jaar', 'middel', 'Beveiligde MR-omgeving, encryptie gevoelige stukken, toegangsbeperking tot persoonlijke gegevens', 'MR-protocol, privacy bij vergaderingen, beperkte openbaarheid persoonlijke standpunten', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(62, 'Internationale uitwisselingen', 'Organiseren van uitwisselingen met buitenlandse scholen', 'Toestemming ouders/leerling; Uitvoering overeenkomst', 'Naam, paspoortgegevens, medische informatie, verzekering, gastgezin matching', 'Deelnemende leerlingen', 'Partner school in buitenland, reisorganisatie, ouders, ambassade (visum)', '1 jaar na terugkeer', 'hoog', 'Versleutelde uitwisseling partner school, beperkte gegevens voor matching, encryptie medische info', 'Uitwisselingsprotocol, uitgebreide oudertoestemming, duidelijke gegevensuitwisseling partner, reisveiligheid', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(63, 'Talentprogramma\'s en plusklassen', 'Aanbieden verrijking aan getalenteerde leerlingen', 'Toestemming ouders/leerling; Uitvoering onderwijsprogramma', 'Selectiecriteria, testresultaten, begeleidingsplannen, evaluaties, bijzondere capaciteiten', 'Geselecteerde leerlingen', 'Talentcoördinator, docenten plusklas, ouders, samenwerkingspartners', '2 jaar na uitstroom programma', 'middel', 'Apart talentvolgsysteem, encryptie testresultaten, beperkte toegang tot selectiegegevens', 'Talentprotocol, privacy bij selectie, ouders volledig informeren, beperkte labeling leerlingen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(64, 'Leerlingvolgsysteem (LVS) en toetsing', 'Afnemen en analyseren van landelijke toetsen', 'Wettelijke verplichting; Uitvoering onderwijsprogramma', 'Toetsresultaten, vaardigheidsniveaus, groeianalyses, adviezen op basis van toetsen', 'Leerlingen', 'Docenten, mentoren, zorgteam, schoolleiding, inspectie (geaggregeerd)', '5 jaar na uitschrijving', 'hoog', 'Beveiligde LVS-omgeving, encryptie individuele resultaten, geanonimiseerde groepsanalyses', 'Toetsprotocol, privacy bij toetsresultaten, zorgvuldig gebruik voor plaatsingsadviezen, ouders informeren', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(65, 'Doorstroomgegevens naar vervolgonderwijs', 'Uitwisselen gegevens met vervolgopleidingen', 'Toestemming leerling/ouders; Gerechtvaardigd belang', 'Naam, doorstroombestemming, advies, cijfers, bijzondere kenmerken (indien relevant)', 'Uitstromende leerlingen', 'Vervolgopleidingen, DUO, gemeente (leerplicht)', '2 jaar na doorstroom', 'hoog', 'Versleutelde uitwisseling, watermerken op doorstroomdocumenten, logging alle uitgaande gegevens', 'Doorstroomprotocol, expliciete toestemming voor uitgebreide informatie, minimale gegevensuitwisseling', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(66, 'Archief en historische documenten', 'Bewaren van schoolarchief voor historische doeleinden', 'Gerechtvaardigd belang (historisch); Wettelijke verplichting', 'Jaarboek foto\'s, examenlijsten, belangrijke documenten, oud-leerling gegevens', 'Oud-leerlingen, voormalig personeel', 'Schoolarchivaris, onderzoekers (toegangsverzoek), oud-leerlingen', 'Permanent voor archiefwaardige documenten', 'middel', 'Digitaal archief met toegangsbeheer, watermerken op documenten, beperkte openbaarheid persoonsgegevens', 'Archiefbeleid, toegangsverzoeken procedure, privacy bij historische documenten, beperkte toegang recente gegevens', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(67, 'Sponsoring en samenwerking bedrijven', 'Samenwerking met bedrijven voor sponsoring en projecten', 'Toestemming; Gerechtvaardigd belang', 'Bedrijfsgegevens, contactpersonen, sponsorbedragen, samenwerkingsovereenkomsten', 'Sponsor bedrijven, contactpersonen', 'Schoolleiding, communicatie, projectleiders, administratie', '5 jaar na einde samenwerking', 'laag', 'CRM voor partners, encryptie financiële gegevens, gescheiden van leerlingdata', 'Sponsorbeleid, privacy clausules in contracten, minimale gegevensuitwisseling met leerlingen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(68, 'Gebruik clouddiensten voor onderwijs', 'Opslag en verwerking via clouddiensten (Office 365, Google Workspace)', 'Uitvoering overeenkomst; Toestemming', 'Inhoud documenten, e-mails, opslag, gebruikersactiviteiten, gedeelde bestanden', 'Leerlingen, personeel', 'Cloudprovider (met verwerkersovereenkomst), systeembeheer, gebruikers onderling', 'Volgens cloudprovider retentie of schoolbeleid', 'hoog', 'Encryptie in transit en at rest, toegangscontrole, logging, datalek preventie tools', 'Cloud gebruik beleid, verwerkersovereenkomsten, bewustwording gebruikers, regelmatige security audits', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(69, 'Digitaal toetsen en proctoring', 'Afnemen van digitale toetsen met online surveillance', 'Uitvoering overeenkomst; Gerechtvaardigd belang (fraudepreventie)', 'Identiteitsverificatie, toetsresultaten, schermopnames, webcam beelden, toetsaanslagen', 'Toetskandidaten', 'Docenten, examencommissie, proctoring dienst (indien extern)', '6 maanden na toets, tenzij beroep (max 2 jaar)', 'hoog', 'Encryptie opnames, watermerken, strikte toegangsbeheer, automatische verwijdering', 'Online toets protocol, duidelijke informatie aan leerlingen, proportionaliteit surveillance, beperkte toegang beelden', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(70, 'Leerling mentor app communicatie', 'Gebruik communicatie apps tussen mentor en leerling/ouders', 'Uitvoering overeenkomst; Toestemming', 'Berichten, bijlagen, contactgegevens, gespreksgeschiedenis', 'Leerlingen, ouders, mentoren', 'Gebruikers binnen app, systeembeheer (technisch), app provider', 'Schooljaar + 1 maand', 'middel', 'End-to-end encryptie, logging beperkt, automatische archivering oudere berichten', 'App gebruik protocol, zakelijk gebruik, geen gevoelige info via app, ouders informeren over gebruik', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(71, 'Gebruik biometrie voor toegang/kantine', 'Toepassen vingerafdruk/gezichtsherkenning voor toegang of betalingen', 'Toestemming; Gerechtvaardigd belang (veiligheid/efficiency)', 'Biometrische templates, gebruikshistorie, saldo (kantine), toegangstijden', 'Gebruikers biometrisch systeem', 'Systeembeheer, financiële administratie (kantine), beveiliging', 'Zolang actief gebruik + 1 maand na beëindiging', 'hoog', 'Opslag biometrische templates (geen afbeeldingen), encryptie, logging toegang tot systeem, apart systeem voor biometrie', 'Biometrie protocol, expliciete toestemming vereist, alternatief aanbieden, regelmatige privacy assessment', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(72, 'Leerlingwelzijn en signalering', 'Systematisch monitoren van welzijn leerlingen en signaleren problemen', 'Vitale belangen; Wettelijke zorgplicht', 'Welzijnsindicatoren, signaleringslijsten, gespreksverslagen, observaties, risico-inschattingen', 'Alle leerlingen', 'Zorgteam, mentoren, schoolleiding, eventueel jeugdzorg (bij zorgen)', '2 jaar na einde signalering', 'hoog', 'Beveiligd signaleringssysteem, encryptie gevoelige observaties, strikte toegangscontrole', 'Signaleringsprotocol, privacy bij welzijnsgegevens, zorgvuldige omgang met vermoedens, DPO betrokkenheid', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(73, 'Gebruik educatieve apps en platforms', 'Inzet van externe educatieve tools in lessen', 'Uitvoering overeenkomst; Toestemming (indien persoonsgegevens)', 'Leerling prestaties in app, gebruikersactiviteiten, ingevoerde data, voortgang', 'Leerlingen gebruikend educatieve apps', 'App provider, docenten, leerlingen (eigen data)', 'Volgens app provider of einde schooljaar', 'middel', 'Beperkte gegevensuitwisseling met apps, pseudonimisering waar mogelijk, encryptie login gegevens', 'Educatieve apps protocol, privacy review voor nieuwe apps, ouders informeren over gebruik, verwerkersovereenkomsten', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(74, 'Onderwijslogistiek en planning', 'Plannen van lessen, lokalen en middelen', 'Uitvoering overeenkomst; Gerechtvaardigd belang', 'Roostergegevens, lokalenbezetting, reserveringen, gebruiksmiddelen', 'Leerlingen, personeel', 'Roostermaker, facilitair beheer, docenten, leerlingen (publieke info)', '1 jaar na schooljaar', 'laag', 'Rooster software met toegangsbeheer, anonieme weergave waar mogelijk, encryptie gevoelige planning', 'Planningsprotocol, privacy bij bijzondere planning (bv. individuele begeleiding), beperkte openbaarheid', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(75, 'Gebruik van AI in onderwijs', 'Inzet kunstmatige intelligentie voor leren en begeleiding', 'Toestemming; Gerechtvaardigd belang (onderwijsverbetering)', 'Leerdata, interacties met AI, gegenereerde adviezen, leerprofielen, eventueel beeld/geluid opnames', 'Leerlingen gebruiken AI-tools', 'AI systeem provider, docenten, onderzoekers (geanonimiseerd)', 'Volgens AI systeem instellingen of einde gebruik', 'hoog', 'Pseudonimisering leerdata, encryptie, logging AI beslissingen, mogelijkheid tot human review', 'AI gebruik protocol, transparantie over AI gebruik, oudertoestemming, regelmatige bias checks, DPO assessment', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(76, 'Leerling vervoer met eigen auto (stage)', 'Registreren leerlingen die met eigen auto naar stage gaan', 'Toestemming ouders/leerling; Wettelijke verplichting (verzekering)', 'Naam, rijbewijsgegevens, kenteken, verzekeringsgegevens, stageadres', 'Stageleerlingen met eigen vervoer', 'Stagebegeleider, verzekeringsmaatschappij, ouders', 'Duur stage + 1 maand', 'middel', 'Versleutelde registratie, beperkte toegang, apart systeem van reguliere stagedata', 'Eigen vervoer protocol, oudertoestemming verplicht, verzekering check, veiligheidsinstructies', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(77, 'Gebruik wearables bij sportlessen', 'Inzet van activity trackers bij lichamelijke opvoeding', 'Toestemming leerlingen/ouders; Onderwijsdoel', 'Hartslag, activiteitsniveau, prestatie data, locatie (indien GPS)', 'Deelnemende leerlingen LO', 'LO docent, leerlingen (eigen data), systeem provider', 'Einde schooljaar', 'middel', 'Pseudonimisering data, lokale opslag (geen cloud), encryptie, beperkte data-retentie', 'Wearables protocol, expliciete toestemming, geen verplichting, privacy by design bij lessen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(78, 'Digitale portfolio\'s leerlingen', 'Bijhouden en delen van digitaal portfolio met werkstukken', 'Uitvoering overeenkomst; Toestemming voor delen', 'Werkstukken, reflecties, beoordelingen, persoonlijke ontwikkelingsdoelen, feedback', 'Leerlingen met digitaal portfolio', 'Leerling zelf, docenten, ouders (toegang mogelijk), eventueel vervolgopleiding', '2 jaar na uitstroom', 'middel', 'Portfolio platform met toegangsbeheer, encryptie opgeslagen bestanden, watermerken bij export', 'Portfolio protocol, leerling eigenaarschap data, toestemming voor extern delen, regelmatige opschoning', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(79, 'Gebruik van drones voor onderwijs', 'Inzet drones bij techniek/beeldende vorming lessen', 'Toestemming; Gerechtvaardigd belang (onderwijs)', 'Beeldmateriaal drone, locatiegegevens, vluchtgegevens, eventueel personen in beeld', 'Leerlingen gebruikend drones, personen in vlieggebied', 'Docent, leerlingen projectgroep, systeembeheer drone', 'Projectduur + 1 maand', 'hoog', 'Geen gezichtsherkenning, beperkte opslag beeldmateriaal, automatische blurring personen, encrypted logs', 'Drone gebruik protocol, luchtvaartregels naleven, privacy impact assessment, beperkt vlieggebied', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(80, 'Leerling begeleiding bij scheiding ouders', 'Registreren en begeleiden bij complexe thuissituaties', 'Vitale belangen; Toestemming ouders', 'Scheidingsregeling, afspraken ouders, communicatievoorkeuren, bijzondere thuissituatie', 'Leerlingen met gescheiden ouders', 'Mentor, zorgteam, beide ouders (volgens afspraken), eventueel jeugdzorg', 'Duur leerling op school + 1 jaar', 'hoog', 'Aparte registratie in zorgdossier, encryptie, strikte toegangscontrole, logging alle toegang', 'Protocol gescheiden ouders, ouderlijk gezag check, duidelijke communicatie afspraken, privacy gevoelige informatie', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(81, 'Gebruik van VR/AR in onderwijs', 'Inzet virtual/augmented reality voor educatieve doeleinden', 'Toestemming; Onderwijsdoel', 'Interacties in VR/AR, leerprestaties in virtuele omgeving, mogelijk beweging/locatie data', 'Leerlingen gebruikend VR/AR', 'Docent, systeem provider, onderzoekers (geanonimiseerd)', 'Einde les/schooljaar', 'middel', 'Pseudonimisering gebruikersdata, lokale verwerking, beperkte data-retentie, encryptie', 'VR/AR gebruik protocol, gezondheids- en veiligheidsinstructies, oudertoestemming voor langdurig gebruik', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(82, 'Leerlingparticipatie bij onderzoek', 'Betrekken leerlingen als medeonderzoekers', 'Toestemming leerlingen/ouders; Onderwijsdoel', 'Onderzoeksdata verzameld door leerlingen, observaties, interview opnames, analyseresultaten', 'Leerlingen als onderzoekers en onderzochten', 'Begeleidende docent, medeleerlingen (in onderzoek), eventueel externe partijen', 'Projectduur + 6 maanden (geanonimiseerd langer)', 'middel', 'Pseudonimisering onderzoeksdata, encryptie opnames, toegangsbeperking tot ruwe data', 'Onderzoeksprotocol leerlingen, ethische richtlijnen, informed consent bij deelnemers, privacy training leerlingen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(83, 'Gebruik van chatbots voor onderwijsondersteuning', 'Inzet AI-chatbots voor vragen en ondersteuning', 'Toestemming; Gerechtvaardigd belang', 'Vraaggeschiedenis, interacties, leerbehoeften, mogelijk emotie-analyse', 'Leerlingen gebruikend chatbot', 'Chatbot systeem, docenten (geaggregeerde inzichten), systeembeheer', 'Chat historie: 3 maanden; Geanonimiseerde data: 1 jaar', 'middel', 'End-to-end encryptie chats, pseudonimisering gebruikers, logging beperkt, menselijke review mogelijkheid', 'Chatbot protocol, transparantie over AI gebruik, geen medische/psychologische adviezen, opt-out mogelijkheid', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(84, 'Leerling bemiddeling bij conflicten', 'Faciliteren peer mediation en conflictbemiddeling', 'Toestemming betrokkenen; Vitale belangen', 'Conflictbeschrijving, bemiddelingsverslagen, afspraken, evaluaties', 'Leerlingen in conflictbemiddeling', 'Peer mediators, begeleidende docent, betrokken leerlingen', '6 maanden na afronding bemiddeling', 'middel', 'Versleutelde verslagen, toegangsbeperking tot bemiddelingsdossiers, automatische verwijdering na termijn', 'Bemiddelingsprotocol, vertrouwelijkheid, toestemming alle partijen, beperkte gegevensvastlegging', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(85, 'Gebruik van smartboards en interactieve schermen', 'Registreren gebruik interactieve schoolborden', 'Gerechtvaardigd belang; Onderwijsdoel', 'Gebruikersinteracties, opgeslagen lessen, schermopnames (indien opgenomen)', 'Docenten gebruikend smartboards, leerlingen in beeld (indien opname)', 'Docent, ICT-beheer, leerlingen (gedeelde lessen)', 'Lesopnames: 1 jaar; Gebruiksdata: 3 maanden', 'laag', 'Encryptie opgeslagen lessen, beperkte logging, toegangscontrole tot opnames', 'Smartboard gebruik protocol, privacy bij opnames lessen, leerlingen informeren over opnames', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(86, 'Leerling begeleiding bij hoogbegaafdheid', 'Specifieke begeleiding voor hoogbegaafde leerlingen', 'Toestemming ouders/leerling; Uitvoering onderwijsprogramma', 'IQ testresultaten, begeleidingsplan, versnellingstraject, sociaal-emotionele begeleiding', 'Hoogbegaafde leerlingen', 'Talentcoördinator, mentor, ouders, eventueel extern specialist', '2 jaar na uitstroom begeleiding', 'hoog', 'Apart hoogbegaafdheid dossier, encryptie testresultaten, strikte toegangscontrole', 'Hoogbegaafdheid protocol, zorgvuldige omgang met label, ouders volledig informeren, privacy gevoelige capaciteiten', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(87, 'Gebruik van gepersonaliseerde leersystemen', 'Inzet adaptive learning systemen', 'Toestemming; Onderwijsdoel', 'Gedetailleerd leerprofil, aanpassingen systeem, voortgang per onderdeel, leerstijlvoorkeuren', 'Leerlingen gebruikend adaptive learning', 'Leersysteem provider, docent, leerling zelf', 'Duur gebruik systeem + 1 jaar', 'hoog', 'Pseudonimisering leerdata, encryptie, export mogelijkheid data, beperkte data-retentie', 'Adaptive learning protocol, transparantie over data gebruik, oudertoestemming, regelmatige privacy review', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(88, 'Leerling betrokkenheid bij schoolfeesten', 'Organiseren en begeleiden van schoolfeesten en activiteiten', 'Toestemming ouders/leerling; Gerechtvaardigd belang', 'Deelnemerslijsten, leeftijdscontrole, toegangscontrole, incidentregistratie', 'Deelnemende leerlingen', 'Feestcommissie, begeleiders, beveiliging, ouders (noodcontact)', '2 maanden na feest', 'middel', 'Digitale aanmelding met encryptie, beperkte gegevens bij toegang, automatische verwijdering na termijn', 'Feestprotocol, leeftijdsgrenzen, privacy bij toegangscontrole, incidenten registratie beperkt', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(89, 'Gebruik van stemkastjes in de klas', 'Inzet van interactieve stemsystemen voor formatieve toetsing', 'Toestemming; Onderwijsdoel', 'Antwoordhistorie, leerling identificatie (indien niet anoniem), voortgang over tijd', 'Leerlingen gebruikend stemkastjes', 'Docent, leerlingen (anonieme resultaten)', 'Einde les of schooljaar (afhankelijk instellingen)', 'laag', 'Anonieme modus waar mogelijk, encryptie data, beperkte koppeling naar individuen', 'Stemkastjes protocol, privacy bij formatieve toetsing, leerlingen informeren over anonieme/geïdentificeerde modus', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(90, 'Leerling begeleiding bij rouw en verlies', 'Ondersteunen bij overlijden of ernstige ziekte in omgeving', 'Vitale belangen; Toestemming ouders/leerling', 'Rouwproces, gespreksverslagen, ondersteuningsbehoefte, contact met externe hulp', 'Leerlingen met verliessituatie', 'Zorgteam, mentor, ouders, eventueel rouwbegeleider', '1 jaar na beëindiging begeleiding', 'hoog', 'Aparte rouwdossiers, encryptie, strikte toegangscontrole, beperkte kring op de hoogte', 'Rouwprotocol, discretie, toestemming leerling/ouders voor registratie, zorgvuldige gegevensvernietiging', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(91, 'Gebruik van sociale media monitoring tools', 'Monitoren van online gedrag leerlingen bij zorgen', 'Vitale belingen; Strikte voorwaarden', 'Publieke sociale media posts, mogelijke risico signalen, geen privé accounts', 'Leerlingen waar zorg over bestaat', 'Zorgteam, schoolleiding (bij acute zorgen), eventueel ouders/politie (bij dreiging)', 'Monitoring periode + 1 maand (tenzij incident)', 'hoog', 'Geen automatische monitoring, handmatige checks, logging reden monitoring, encryptie bevindingen', 'Social media monitoring protocol, alleen bij concrete zorgen, proportionaliteit, DPO toetsing vooraf', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(92, 'Leerling inzet als tutor/mentor', 'Inzet ouderejaars als tutor voor jongere leerlingen', 'Toestemming tutor en leerling/ouders; Onderwijsdoel', 'Koppeling tutor-leerling, voortgangsverslagen, evaluaties, bijscholing tutor', 'Tutors en getutorde leerlingen', 'Tutorcoördinator, mentoren betrokken leerlingen, ouders', 'Einde tutorrelatie + 6 maanden', 'laag', 'Beperkte gegevensregistratie, encryptie evaluaties, toegangsbeperking tot persoonlijke notities', 'Tutorprotocol, privacy bij tutor-leerling relatie, toestemming alle partijen, duidelijke grenzen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(93, 'Gebruik van plagiarism detection software', 'Controleren op plagiaat in werkstukken en opdrachten', 'Gerechtvaardigd belang (academische integriteit); Uitvoering overeenkomst', 'Ingediende werkstukken, bronvermelding checks, plagiaat rapporten, student identificatie', 'Leerlingen inleverend werkstukken', 'Docent, examencommissie (bij fraude), software provider', 'Werkstukken: 1 jaar na beoordeling; Fraudegevallen: 2 jaar', 'middel', 'Encryptie ingediende documenten, watermerken op rapporten, logging controles, beperkte data-retentie bij provider', 'Plagiaat protocol, transparantie over gebruik software, leerlingen informeren vooraf, proportionaliteit bij checks', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(94, 'Leerling participatie in debat en model VN', 'Organiseren debatactiviteiten en model United Nations', 'Toestemming; Onderwijsdoel', 'Deelnemersinformatie, standpunten, beoordelingen, reisgegevens (indien extern)', 'Deelnemende leerlingen', 'Begeleidende docent, organisatoren externe evenementen, medeleerlingen', '1 jaar na activiteit', 'laag', 'Beperkte persoonsgegevens bij externe deelname, encryptie reisgegevens, watermerken op documenten', 'Debat/MUN protocol, privacy bij gevoelige standpunten, oudertoestemming voor externe deelname', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(95, 'Gebruik van eye-tracking bij onderzoek', 'Inzet eye-tracking voor onderwijsonderzoek', 'Toestemming leerlingen/ouders; Onderzoeksdoel', 'Oogbewegingsdata, aandachtspatronen, leerproces analyse, eventueel beeld van gezicht', 'Deelnemende leerlingen onderzoek', 'Onderzoekers, begeleidende docent, onderzoeksinstelling', 'Onderzoeksperiode + 6 maanden (geanonimiseerd langer)', 'hoog', 'Pseudonimisering oogbewegingsdata, encryptie, aparte opslag van identificerende gegevens, beperkte retentie', 'Eye-tracking protocol, uitgebreide informed consent, ethische review, privacy by design onderzoek', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(96, 'Leerling begeleiding bij eetstoornissen', 'Signaleren en begeleiden bij vermoedens eetstoornissen', 'Vitale belangen; Toestemming ouders/leerling', 'Signalen, gespreksverslagen, contact met hulpverlening, bijzondere persoonsgegevens (gezondheid)', 'Leerlingen met vermoedens eetstoornis', 'Zorgteam, mentor, ouders, GGZ/hulpverlening', 'Duur begeleiding + 1 jaar', 'hoog', 'Apart zorgdossier, encryptie, strikte toegangscontrole, logging alle toegang', 'Eetstoornis protocol, discretie, oudertoestemming voor externe hulp, multidisciplinaire aanpak', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(97, 'Gebruik van virtual classrooms', 'Faciliteren online lessen en afstandsonderwijs', 'Uitvoering overeenkomst; Gerechtvaardigd belang', 'Deelnamelijsten, chatgeschiedenis, opgenomen lessen, scherm delen opnames, aanwezigheid', 'Deelnemende leerlingen en docenten', 'Virtual classroom provider, docenten, leerlingen (opgenomen lessen)', 'Opnames: 1 jaar; Deelnamegegevens: 6 maanden', 'middel', 'Encryptie live sessies, toegangscontrole opnames, watermerken op opnames, logging toegang', 'Virtual classroom protocol, privacy bij opnames, leerlingen informeren over opnamebeleid, beveiligde inlog', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(98, 'Leerling participatie in kunst en cultuur', 'Organiseren kunstprojecten en culturele activiteiten', 'Toestemming; Onderwijsdoel', 'Deelnemersinformatie, kunstwerken, optredens opnames, evaluaties', 'Deelnemende leerlingen kunst/cultuur', 'Kunstvakdocenten, externe kunstenaars, ouders (voorstellingen), eventueel publiek', 'Projectduur + 1 jaar', 'laag', 'Watermerken op digitale kunstwerken, beperkte toegang tot persoonlijke projectdocumenten, encryptie opnames', 'Kunst & cultuur protocol, toestemming voor publicatie/optreden, privacy bij persoonlijke kunstuitingen', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(99, 'Gebruik van sensoren in practicumlokalen', 'Inzet sensoren voor natuurwetenschappelijke experimenten', 'Toestemming; Onderwijsdoel', 'Experiment data, meetresultaten, mogelijk locatie binnen lokaal, groeps samenstelling', 'Leerlingen uitvoerend practicum', 'Docent, leerlingen onderzoeksgroep, systeembeheer sensornetwerk', 'Einde practicumreeks + 3 maanden', 'laag', 'Anonieme data verzameling waar mogelijk, encryptie sensordata, beperkte koppeling naar individuen', 'Sensor gebruik protocol, privacy bij locatiegegevens, leerlingen informeren over datacollectie', 'nee', '2025-12-30 15:00:00', '2025-12-30 15:00:00'),
(100, 'Leerling begeleiding bij genderidentiteit', 'Ondersteunen bij vragen rond genderidentiteit en coming-out', 'Vitale belangen; Toestemming leerling', 'Genderidentiteit, gewenste aanspreekvorm, gespreksverslagen, ondersteuningsbehoefte', 'Leerlingen met vragen genderidentiteit', 'Vertrouwenspersoon, zorgteam (indien nodig), ouders (met toestemming leerling)', 'Duur ondersteuning + 1 jaar', 'hoog', 'Apart vertrouwelijk dossier, encryptie, strikte toegangscontrole, logging alle toegang', 'Genderidentiteit protocol, discretie, regie bij leerling over informatie delen, oudertoestemming alleen indien leerling akkoord', 'ja', '2025-12-30 15:00:00', '2025-12-30 15:00:00');

--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `avg_register`
--
ALTER TABLE `avg_register`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_risiconiveau` (`risiconiveau`),
  ADD KEY `idx_dpia_vereist` (`dpia_vereist`);

--
-- AUTO_INCREMENT voor geëxporteerde tabellen
--

--
-- AUTO_INCREMENT voor een tabel `avg_register`
--
ALTER TABLE `avg_register`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;